name: Android CI

on:
  push:
    branches: [ "**" ]
    paths-ignore:
      - '**/*.md'
  pull_request_review:
    types:
      - submitted
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Decode and create xed.keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 -d > /tmp/xed.keystore

      - name: Decode and create signing.properties
        run: echo "${{ secrets.PROP }}" | base64 -d > /tmp/signing.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease --stacktrace && mv app/build/outputs/apk/release/*apk app/karbon.apk
        env:
          KEYSTORE_FILE: /tmp/xed.keystore
          SIGNING_PROPERTIES_FILE: /tmp/signing.properties

      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/karbon.apk

      - name: Delete xed.keystore and signing.properties
        run: rm /tmp/xed.keystore /tmp/signing.properties